version: '3.8'
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.7.0
    ports:
      - "5044:5044"
    networks:
      - es-bridge
    depends_on:
      - es
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline

networks:
  es-bridge:
    driver: bridge
